@hostname=localhost
@port=3000
@host=http://{{hostname}}:{{port}}
@bearer_token = Bearer token-from-login-endpoint

### register user
POST {{host}}/register
Content-Type: application/json

{
    "email": "john@email.com",
    "name": "John Doe",
    "password": "SuperSecretPassword123"
}

### login user
POST {{host}}/login
Content-Type: application/json

{
    "email": "john@email.com",
    "password": "SuperSecretPassword123"
}

### get users
GET {{host}}/api/users
Content-Type: application/json
Authorization: {{bearer_token}}

### create customer
POST {{host}}/api/customers/create
Content-Type: application/json
Authorization: {{bearer_token}}

{
    "name": "Cutomer 1"
}

### get customers
GET {{host}}/api/customers
Content-Type: application/json
Authorization: {{bearer_token}}

### create complaint
POST {{host}}/api/complaints/create
Content-Type: application/json
Authorization: {{bearer_token}}

{
    "customername": "Customer 1",
    "description": "Description"
    "category": 1
    "priority": 1
    "status": 1
}

### edit complaint
PUT {{host}}/api/complaints/edit/1
Content-Type: application/json
Authorization: {{bearer_token}}

{
    "description": "Edited Description",
    "category": 2
    "priority": 2
    "status": 2
}

### get complaint by id
GET {{host}}/api/complaints/1
Content-Type: application/json
Authorization: {{bearer_token}}

### get complaint
GET {{host}}/api/complaints?sortOrder=desc
Content-Type: application/json
Authorization: {{bearer_token}}

### create complaint comment
POST {{host}}/api/comments/create/1
Content-Type: application/json
Authorization: {{bearer_token}}

{
    "comment": "New comment"
}

### create category
POST {{host}}/api/categories/create
Content-Type: application/json
Authorization: {{bearer_token}}

{
    "name": "Kategori 1"
}

### get categories
GET {{host}}/api/categories
Content-Type: application/json
Authorization: {{bearer_token}}

